export const ACCOUNT_PLACEHOLDER = '최대 8글자의 결제수단명을 입력해주세요.';
export const CATEGORY_PLACEHOLDER = '최대 8글자의 카테고리명을 입력해주세요.';
export const CREATE_ACCOUNT_MODAL_NAME = '결제수단 생성';
export const CREATE_INCOME_CATEGORY_MODAL_NAME = '수입 카테고리 생성';
export const CREATE_EXPENDITURE_CATEGORY_MODAL_NAME = '지출 카테고리 생성';
export const UPDATE_INCOME_CATEGORY_MODAL_NAME = '수입 카테고리 편집';
export const UPDATE_EXPENDITURE_CATEGORY_MODAL_NAME = '지출 카테고리 편집';
export const ACCOUNT_LABEL_NAME = '결제수단 이름';
export const CATEGORY_LABEL_NAME = '카테고리 이름';
export const UPDATE_ACCOUNT_MODAL_NAME = '결제수단 편집';
export const UPDATE_CATEGORY_MODAL_NAME = '카테고리 편집';
export const SMS_DESCRIPTION = '문자 메시지를 입력하면 해당 문자의 내용을 거래내역으로 자동 변환해주는 기능입니다.';

const formModal = {
  ACCOUNT_PLACEHOLDER,
  CATEGORY_PLACEHOLDER,
  CREATE_ACCOUNT_MODAL_NAME,
  CREATE_INCOME_CATEGORY_MODAL_NAME,
  CREATE_EXPENDITURE_CATEGORY_MODAL_NAME,
  UPDATE_INCOME_CATEGORY_MODAL_NAME,
  UPDATE_EXPENDITURE_CATEGORY_MODAL_NAME,
  CREATE_CATEGORY_MODAL_NAME,
  ACCOUNT_LABEL_NAME,
  CATEGORY_LABEL_NAME,
  UPDATE_ACCOUNT_MODAL_NAME,
  UPDATE_CATEGORY_MODAL_NAME,
  SMS_DESCRIPTION,
};

export default formModal;
